using System.Globalization;
using System.Text;
using System.Text.Json;
using MDKOSS.Core;

namespace MDKOSS.Iec61131;

public sealed class IecExportResult
{
    public string Directory { get; init; } = "";
    public IReadOnlyList<string> Files { get; init; } = [];
    public IecProject Project { get; init; } = new();
}

/// <summary>Writes SCL, PLCopen XML, IO map and a human report to a folder.</summary>
public static class IecExport
{
    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public static IecExportResult Write(IecProject project, string outputDirectory)
    {
        ArgumentNullException.ThrowIfNull(project);
        if (string.IsNullOrWhiteSpace(outputDirectory))
        {
            throw new ArgumentException("output directory is required", nameof(outputDirectory));
        }

        Directory.CreateDirectory(outputDirectory);
        Directory.CreateDirectory(Path.Combine(outputDirectory, "scl"));

        var files = new List<string>();
        void Save(string rel, string content)
        {
            var path = Path.Combine(outputDirectory, rel.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            files.Add(path);
        }

        foreach (var kv in SclWriter.WriteFiles(project))
        {
            Save(kv.Key, kv.Value);
        }

        Save("plcopen.xml", PlcOpenXmlWriter.Write(project));
        Save("mapping.json", JsonSerializer.Serialize(new
        {
            project = project.Name,
            cycleMs = project.CycleMs,
            io = project.IoPoints.Select(p => new
            {
                p.Name,
                p.Alias,
                p.DeviceId,
                p.MdkAddress,
                p.AtAddress,
                p.IsOutput,
                p.Label,
            }),
            globals = project.Globals.Select(g => new { g.Name, type = IecTypeMap.ToSt(g.Type), g.SourceKey, g.Init }),
            nodes = project.NodeMaps,
            notes = project.Notes,
        }, JsonOpts));
        Save("REPORT.txt", WriteReport(project));
        Save("README.md", WriteReadme(project));

        return new IecExportResult
        {
            Directory = outputDirectory,
            Files = files,
            Project = project,
        };
    }

    public static IecExportResult FromSetting(MdkSetting setting, string outputDirectory, string? settingDirectory = null)
    {
        ArgumentNullException.ThrowIfNull(setting);
        var project = IecProjectBuilder.FromSetting(setting, settingDirectory);
        return Write(project, outputDirectory);
    }

    public static IecExportResult FromSettingFile(string settingPath, string outputDirectory)
    {
        var setting = MdkSetting.Load(settingPath);
        return FromSetting(setting, outputDirectory, Path.GetDirectoryName(Path.GetFullPath(settingPath)));
    }

    private static string WriteReport(IecProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"MDKOSS → IEC 61131 export: {project.Name}");
        sb.AppendLine($"Cycle: {project.CycleMs.ToString(CultureInfo.InvariantCulture)} ms");
        sb.AppendLine($"POUs: {project.Pous.Count.ToString(CultureInfo.InvariantCulture)}");
        sb.AppendLine($"IO points: {project.IoPoints.Count.ToString(CultureInfo.InvariantCulture)}");
        sb.AppendLine($"Globals: {project.Globals.Count.ToString(CultureInfo.InvariantCulture)}");
        sb.AppendLine();
        sb.AppendLine("Notes:");
        if (project.Notes.Count == 0)
        {
            sb.AppendLine("  (none)");
        }

        foreach (var n in project.Notes)
        {
            sb.AppendLine($"  [{n.Severity}] {n.Message}");
        }

        sb.AppendLine();
        sb.AppendLine("POUs:");
        foreach (var p in project.Pous)
        {
            sb.AppendLine($"  {p.Kind} {p.Name}  source={p.SourceName}  steps={p.Steps.Count}  cyclic={p.Cyclic} loop={p.Loop}");
        }

        return sb.ToString();
    }

    private static string WriteReadme(IecProject project) =>
        $"""
        # {project.Name} — IEC 61131 export

        Generated by `MDKOSS.Iec61131`. Import into TIA Portal / CODESYS as Structured Text.

        | File | Use |
        |---|---|
        | `plcopen.xml` | PLCopen TC6 interchange (IEC 61131-10) |
        | `scl/*.scl` | Siemens-style SCL source (GVL, host stubs, task FBs, PROGRAM_Main) |
        | `mapping.json` | GPIO alias → `%I/%Q`, vars, Flow node → step |
        | `REPORT.txt` | Warnings (PC-only tasks, unmapped IO) |

        ## Semantics

        - Each `type=flow` task becomes a function block with a `CASE iStep` sequencer (non-blocking `TON` / host FBs).
        - GPIO aliases map to `VAR_GLOBAL ... AT %I/%Q`.
        - `setting.vars` map to GVL.
        - Motion / `deviceAction` become Execute→Done handshake stubs (`01_FB_HostStubs.scl`). Replace with S7-1500 TO or keep as PC handshake.
        - C# `MotionTask` types are **not** compiled; only Flow graphs.

        Assign `PROGRAM_Main` to a cyclic OB (~{project.CycleMs} ms).
        """;
}
