<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>MDKOSS.Config.Wpf</RootNamespace>
    <AssemblyName>MDKOSS.Config.Wpf</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MDKOSS.Core\MDKOSS.Core.csproj" />
    <ProjectReference Include="..\MDKOSS.Extensions\MDKOSS.Extensions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="configs\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Debug\**\*.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Resource Include="Assets\app.ico" />
  </ItemGroup>
  <Import Project="..\MdkPlugins.targets" />
</Project>
