using System.Drawing;
using System.Drawing.Imaging;
using System.Text;
using MDKOSS.Core;

namespace MDKOSS.Sample.SampleExt;

/// <summary>
/// Renders a PNG "run screenshot" from the current <see cref="RuntimeSnapshot"/>
/// so Sample can preview or publish status without a desktop capture.
/// </summary>
public static class SampleRunScreenshot
{
    public static byte[] RenderPng(RuntimeSnapshot snapshot)
    {
        ArgumentNullException.ThrowIfNull(snapshot);

        const int width = 960;
        const int rowH = 22;
        var deviceLines = snapshot.Devices.Count;
        var driverLines = snapshot.Drivers.Count;
        var height = Math.Max(420, 140 + (deviceLines + driverLines) * rowH + 80);

        using var bmp = new Bitmap(width, height, PixelFormat.Format32bppArgb);
        using var g = Graphics.FromImage(bmp);
        g.Clear(Color.FromArgb(255, 11, 18, 32));
        g.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.AntiAlias;
        g.TextRenderingHint = System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;

        using var titleFont = new Font("Segoe UI", 18f, FontStyle.Bold);
        using var bodyFont = new Font("Consolas", 11f, FontStyle.Regular);
        using var mutedFont = new Font("Segoe UI", 10f, FontStyle.Regular);
        using var titleBrush = new SolidBrush(Color.FromArgb(255, 230, 238, 252));
        using var mutedBrush = new SolidBrush(Color.FromArgb(255, 138, 160, 192));
        using var okBrush = new SolidBrush(Color.FromArgb(255, 53, 208, 143));
        using var accentBrush = new SolidBrush(Color.FromArgb(255, 61, 139, 253));
        using var linePen = new Pen(Color.FromArgb(255, 36, 53, 82));

        var y = 24f;
        g.DrawString("MDKOSS Sample 运行截图", titleFont, titleBrush, 24, y);
        y += 36;
        g.DrawString(
            $"{DateTime.Now:yyyy-MM-dd HH:mm:ss}  |  v{snapshot.Version}",
            mutedFont,
            mutedBrush,
            24,
            y);
        y += 28;
        g.DrawLine(linePen, 24, y, width - 24, y);
        y += 16;

        g.DrawString($"项目: {snapshot.ProjectName}", bodyFont, titleBrush, 24, y);
        y += rowH;
        g.DrawString(
            $"运行中: {(snapshot.IsRunning ? "YES" : "NO")}",
            bodyFont,
            snapshot.IsRunning ? okBrush : mutedBrush,
            24,
            y);
        y += rowH + 8;

        g.DrawString("Drivers", mutedFont, accentBrush, 24, y);
        y += rowH;
        foreach (var (id, drv) in snapshot.Drivers.OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase))
        {
            var conn = drv.IsConnected ? "connected" : "offline";
            g.DrawString($"  {id,-16} type={drv.Type,-8} {conn}", bodyFont, titleBrush, 24, y);
            y += rowH;
        }

        y += 6;
        g.DrawString("Devices", mutedFont, accentBrush, 24, y);
        y += rowH;
        foreach (var (id, dev) in snapshot.Devices.OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase))
        {
            g.DrawString(
                $"  {id,-18} {dev.Type,-14} {dev.State}",
                bodyFont,
                titleBrush,
                24,
                y);
            y += rowH;
            if (y > height - 48)
            {
                break;
            }
        }

        y = height - 36;
        g.DrawString("generated by /api/sampleext/run-screenshot.png", mutedFont, mutedBrush, 24, y);

        using var ms = new MemoryStream();
        bmp.Save(ms, ImageFormat.Png);
        return ms.ToArray();
    }

    /// <summary>Build a DingTalk markdown body that mirrors the screenshot content.</summary>
    public static string BuildMarkdown(RuntimeSnapshot snapshot, string? imageUrl = null)
    {
        ArgumentNullException.ThrowIfNull(snapshot);
        var sb = new StringBuilder();
        sb.AppendLine("### MDKOSS Sample 运行截图");
        sb.AppendLine();
        sb.AppendLine($"- 时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"- 项目: {snapshot.ProjectName}");
        sb.AppendLine($"- 版本: {snapshot.Version}");
        sb.AppendLine($"- 运行中: {(snapshot.IsRunning ? "YES" : "NO")}");
        sb.AppendLine($"- 驱动数: {snapshot.Drivers.Count}");
        sb.AppendLine($"- 设备数: {snapshot.Devices.Count}");
        sb.AppendLine();
        sb.AppendLine("**Devices**");
        sb.AppendLine();
        foreach (var (id, dev) in snapshot.Devices.OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase).Take(12))
        {
            sb.AppendLine($"- `{id}` {dev.Type} / {dev.State}");
        }

        if (!string.IsNullOrWhiteSpace(imageUrl))
        {
            sb.AppendLine();
            sb.AppendLine($"![sample-run]({imageUrl})");
        }

        return sb.ToString();
    }

    public static bool LooksLikePng(ReadOnlySpan<byte> bytes)
        => bytes.Length > 8
           && bytes[0] == 0x89
           && bytes[1] == 0x50
           && bytes[2] == 0x4E
           && bytes[3] == 0x47;
}
