<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MDKOSS.Sample</RootNamespace>
    <AssemblyName>MDKOSS.Sample</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MDKOSS.Core\MDKOSS.Core.csproj" />
    <ProjectReference Include="..\MDKOSS.Extensions\MDKOSS.Extensions.csproj" />
    <ProjectReference Include="..\MDKOSS.Cef\MDKOSS.Cef.csproj" />
    <ProjectReference Include="..\..\examples\pnp\MDKOSS.Pnp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="configs\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="views\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\examples\pnp\configs\**\*">
      <Link>configs\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\examples\pnp\views\**\*">
      <Link>views\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\MDKOSS.Extensions.Camera\configs\**\*">
      <Link>configs\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\MDKOSS.Extensions.PyScript\configs\**\*">
      <Link>configs\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\MDKOSS.Extensions.ModServer\configs\**\*">
      <Link>configs\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\MdkPlugins.targets" />
</Project>
