<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MDKOSS</RootNamespace>
    <AssemblyName>MDKOSS.Extensions</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MDKOSS.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="*.md" />
  </ItemGroup>
</Project>
